version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: python3 app.py
    shm_size: '2gb'  # Increased shared memory for browser st