services:
  - type: web
    name: linkedin-scraper
    env: docker
    region: oregon  # Choose your preferred region
    plan: free  # or choose paid plan as needed
    branch: main
    dockerCommand: python3 app.py
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: LINKEDIN_USERNAME
        sync: false  # Marks this as a secret
      - key: LINKEDIN_PASSWORD
        sync: false
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1